// The three-view turnaround row shown above an element's prompt segment:
// profile, 30° down and top down, each on white, generated by Nano Banana 2.

import { SignInPrompt, signInRequiredFrom } from '@runway/bay-react/runway-sign-in';
import { ImageOff, LoaderCircle, RotateCw, Sparkles } from 'lucide-react';
import { useMemo, useState } from 'react';

import { TURNAROUND_VIEWS } from '../../shared/turnaround.ts';
import { expectedSeconds, useProgress } from '../lib/progress.ts';
import { isForbidden, type LiveTurnaround, type ViewStatus } from '../lib/useTurnarounds.ts';
import { Alert } from '../ui/Alert.tsx';
import { Button } from '../ui/Button.tsx';
import { ProgressBar } from '../ui/ProgressBar.tsx';
import styles from './TurnaroundRow.module.css';

export function TurnaroundRow({
  label,
  title,
  urls,
  live,
  onGenerate,
}: {
  label: string;
  title: string;
  urls: Array<string | null>;
  live: LiveTurnaround | undefined;
  onGenerate: () => void;
}) {
  const [broken, setBroken] = useState<Record<string, true>>({});
  const statuses: ViewStatus[] = TURNAROUND_VIEWS.map((_, i) => {
    const s = live?.views[i];
    if (s === 'running' || s === 'queued' || s === 'error') return s;
    return urls[i] ? 'done' : 'idle';
  });
  const busy = statuses.some((s) => s === 'running' || s === 'queued');
  const hasAny = urls.some(Boolean);
  const signIn = live?.error ? signInRequiredFrom(live.cause) : null;
  const forbidden = live?.error ? isForbidden(live.cause) : false;
  const startedAt = busy && statuses[0] !== 'queued' ? (live?.startedAt ?? null) : null;
  // The profile view first, then the other two side by side: about two views' time.
  // Re-read once per run, when the learned timings may have changed.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const expected = useMemo(() => 2 * expectedSeconds('turnaround-view'), [startedAt]);
  const progress = useProgress('turnaround-view', startedAt, null, expected);

  return (
    <div className={styles.turnaround}>
      <div className={styles.head}>
        {busy ? (
          progress ? (
            <ProgressBar size="sm" label="Generating with Nano Banana 2" progress={progress} />
          ) : (
            <span className={styles.working} role="status" aria-live="polite">
              <LoaderCircle size={14} className={styles.spinner} aria-hidden />
              Waiting to start
            </span>
          )
        ) : (
          <Button
            size="sm"
            variant="ghost"
            icon={hasAny ? <RotateCw size={14} aria-hidden /> : <Sparkles size={14} aria-hidden />}
            aria-label={`${hasAny ? 'Generate again' : 'Generate'} turnaround for ${label}`}
            disabled={forbidden}
            onPress={onGenerate}
          >
            {hasAny ? 'Generate again' : 'Generate turnaround'}
          </Button>
        )}
      </div>

      <div className={styles.row}>
        {TURNAROUND_VIEWS.map((v, i) => {
          const url = urls[i];
          const status = statuses[i];
          const showImage = url && status === 'done' && !broken[url];
          return (
            <figure key={v.id} className={styles.view}>
              <div className={styles.frame}>
                {showImage ? (
                  <a
                    href={url}
                    target="_blank"
                    rel="noreferrer"
                    className={styles.link}
                    aria-label={`Open ${label} ${v.label} view full size`}
                  >
                    <img
                      src={url}
                      alt={`${title}, ${v.label} view`}
                      className={styles.img}
                      loading="lazy"
                      onError={() => setBroken((b) => ({ ...b, [url]: true }))}
                    />
                  </a>
                ) : status === 'running' ? (
                  <LoaderCircle size={18} className={styles.spinner} aria-label={`Generating ${v.label} view`} />
                ) : url && broken[url] ? (
                  <span className={styles.empty}>
                    <ImageOff size={16} aria-hidden />
                    Link expired
                  </span>
                ) : (
                  <span className={styles.empty}>{status === 'queued' ? 'Queued' : status === 'error' ? 'Failed' : 'Not generated'}</span>
                )}
              </div>
              <figcaption className={styles.caption}>{v.label}</figcaption>
            </figure>
          );
        })}
      </div>

      {live?.error &&
        !busy &&
        (signIn ? (
          <SignInPrompt
            reauth={signIn.reauth}
            onSignedIn={onGenerate}
            description="Turnaround images run on your own Runway account and use your own credits."
          />
        ) : (
          <Alert tone="error" title={forbidden ? "Your plan can't run Nano Banana 2" : "Some views didn't generate"}>
            {forbidden
              ? "The signed-in Runway account's plan doesn't include Nano Banana 2, so turnarounds can't be generated."
              : live.error}
          </Alert>
        ))}
    </div>
  );
}
